//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Deposit
    {
        public int Id { get; set; }
        public Nullable<double> Amount { get; set; }
        public string Comment { get; set; }
        public Nullable<System.DateTime> DatenTime { get; set; }
        public Nullable<int> FK_Deposit_DepositHead { get; set; }
    
        public virtual DepositHead DepositHead { get; set; }
    }
}
