//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Expence
    {
        public int Id { get; set; }
        public Nullable<int> Amount { get; set; }
        public string Comment { get; set; }
        public Nullable<System.DateTime> DatenTime { get; set; }
        public Nullable<int> FK_Expence_ExpenceHead { get; set; }
        public Nullable<int> FK_Expence_ExpenceSubHead { get; set; }
    
        public virtual ExpenceHead ExpenceHead { get; set; }
        public virtual ExpenceSubHead ExpenceSubHead { get; set; }
    }
}
