//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Staff
    {
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string Phone { get; set; }
        public string Address { get; set; }
        public Nullable<double> Salary { get; set; }
        public Nullable<System.DateTime> JoiningDate { get; set; }
        public string Designation { get; set; }
        public Nullable<int> FK_Staff_StaffCategory { get; set; }
    
        public virtual StaffCategory StaffCategory { get; set; }
    }
}
